// Reflection loop (Layer B): cluster confirmed leaves by stack signature and
// emit refined recipe SKILL.md files into ~/.pi/agent/vibehack/skills/learned/.
//
// Scope (Phase 6): SUCCESS path only. Falsifier specialists are out of scope.
// Writes ONLY to learned/. Shipped recipes (skills/recipes/, skills/specialists/)
// are read-only territory.
//
// Clustering: string-equality on (kind | recipe | specialist | surface-without-query).
// Embedding-based fallback is out of scope for v1.1.

import * as fs from "node:fs";
import * as path from "node:path";
import { readEvents } from "./events.ts";

export interface Leaf {
  kind: string;
  recipe?: string;
  specialist?: string;
  surface?: string;
  outcome: "confirmed" | "failed";
}

export interface Cluster {
  signature: string;
  leaves: Leaf[];
}

export interface ReflectionOpts {
  eventsPath: string;       // absolute path to events.jsonl
  learnedDir: string;       // ~/.pi/agent/vibehack/skills/learned/
  specialistsDir?: string;  // ~/.pi/agent/vibehack/specialists/learned/ (Phase 7+)
  scope: "compact" | "complete" | "manual";
}

export interface ReflectionResult {
  writtenSkills: string[];
  writtenSpecialists: string[];
  skippedOperatorOwned?: string[];
}

function isOperatorOwned(filePath: string): boolean {
  // Returns true if file exists and lacks the auto_generated: true marker (operator hand-edited).
  if (!fs.existsSync(filePath)) return false;
  try {
    const content = fs.readFileSync(filePath, "utf8");
    const fmMatch = content.match(/^---\s*\n([\s\S]*?)\n---/);
    if (!fmMatch) return true;  // no frontmatter → operator-shaped, skip
    return !/auto_generated:\s*true/.test(fmMatch[1]);
  } catch {
    return false;  // can't read → don't block on permission errors
  }
}

export function extractSignature(leaf: Leaf): string {
  const surfaceClean = (leaf.surface ?? "").split("?")[0];
  return [
    leaf.kind || "_",
    leaf.recipe ?? "_",
    leaf.specialist ?? "_",
    surfaceClean,
  ].join("|");
}

export function clusterBySignature(leaves: Leaf[], minCardinality = 2): Cluster[] {
  const map = new Map<string, Leaf[]>();
  for (const l of leaves) {
    const sig = extractSignature(l);
    if (!map.has(sig)) map.set(sig, []);
    map.get(sig)!.push(l);
  }
  return [...map.entries()]
    .filter(([, ls]) => ls.length >= minCardinality)
    .map(([signature, ls]) => ({ signature, leaves: ls }));
}

// RESUME deviation #15: empty/all-symbol input → "untargeted" (NOT empty string).
function slugify(input: string): string {
  const cleaned = (input ?? "")
    .replace(/[^a-z0-9]+/gi, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
  return cleaned || "untargeted";
}

function priorityForSize(n: number): "low" | "high" {
  return n >= 5 ? "high" : "low";
}

function renderSkillMd(cluster: Cluster, priority: "low" | "high"): string {
  const sample = cluster.leaves[0];
  const namePart = `${slugify(sample.kind)}-${slugify(sample.recipe ?? "x")}`;
  return `---
name: learned-${namePart}
description: Auto-generated recipe from ${cluster.leaves.length} confirmed leaves with signature \`${cluster.signature}\`
priority: ${priority}
auto_generated: true
generated_at: ${new Date().toISOString()}
---

# Vibehack pattern: ${sample.kind || "(untargeted)"} on ${sample.surface ?? "(varied)"}

Observed ${cluster.leaves.length} confirmed cases with this signature. When the planner sees a similar surface, prefer:

- Recipe: \`${sample.recipe ?? "(none)"}\`
- Specialist: \`${sample.specialist ?? "(none)"}\`
- Surface pattern: \`${sample.surface ?? "(varied)"}\`

(This file was auto-generated by reflection. Edit freely or delete.)
`;
}

/**
 * Read events by delegating to readEvents(). Accepts an explicit eventsPath
 * for caller convenience, but the basename MUST be "events.jsonl" — that is
 * the only filename readEvents() supports, and we refuse to silently use a
 * different parser for non-standard names.
 */
async function loadEvents(eventsPath: string): Promise<any[]> {
  const dir = path.dirname(eventsPath);
  const base = path.basename(eventsPath);
  if (base !== "events.jsonl") {
    throw new Error(`reflection requires events.jsonl filename, got: ${base}`);
  }
  return await readEvents(dir);
}

export async function runReflection(opts: ReflectionOpts): Promise<ReflectionResult> {
  const result: ReflectionResult = { writtenSkills: [], writtenSpecialists: [] };

  // Enforce filename invariant up front so the error is not swallowed below.
  const base = path.basename(opts.eventsPath);
  if (base !== "events.jsonl") {
    throw new Error(`reflection requires events.jsonl filename, got: ${base}`);
  }

  let events: any[];
  try {
    events = await loadEvents(opts.eventsPath);
  } catch {
    return result;
  }
  if (!events || events.length === 0) return result;

  const confirmed: Leaf[] = events
    .filter((e: any) => e?.event === "confirm")
    .map((e: any) => ({
      kind: e.kind ?? "",
      recipe: e.recipe,
      specialist: e.specialist,
      surface: e.surface,
      outcome: "confirmed" as const,
    }));

  const clusters = clusterBySignature(confirmed);

  for (const cluster of clusters) {
    const sample = cluster.leaves[0];
    // Slug each component separately so all-symbol input → "untargeted"
    // (RESUME deviation #15) instead of being absorbed by neighboring components.
    const slug = [
      slugify(sample.kind),
      slugify(sample.recipe ?? ""),
      slugify(sample.specialist ?? ""),
    ].join("-");
    const skillPath = path.join(opts.learnedDir, slug, "SKILL.md");
    // Hard guard: never escape learned/.
    if (!skillPath.includes("learned")) continue;
    if (isOperatorOwned(skillPath)) {
      result.skippedOperatorOwned ??= [];
      result.skippedOperatorOwned.push(skillPath);
      continue;  // operator took ownership; don't clobber
    }
    const priority = priorityForSize(cluster.leaves.length);
    fs.mkdirSync(path.dirname(skillPath), { recursive: true });
    fs.writeFileSync(skillPath, renderSkillMd(cluster, priority), "utf8");
    result.writtenSkills.push(skillPath);
  }

  return result;
}
